### ISSUE TITLE
Can't run MoDE with OpenModelica 1.6.1

### ISSUE THREAD

**Issue by Satinelamp** [THM-MoTE/MoDE#2]
I can't run MoDE with OpenModelica 1.6.1, it is stuck on the Start interface.
![1](https://user-images.githubusercontent.com/62006565/99562794-81730780-2a03-11eb-8ae4-e54674344231.png)
![2](https://user-images.githubusercontent.com/62006565/99562800-82a43480-2a03-11eb-84a1-2e59ea8076f4.png)

**Comment by CSchoel** [comment]
Unfortunately, MoDE is currently still in an experimental stage and has no active maintainer. It was developed in the context of a bachelor's thesis, but never fully finished. I am afraid the program is not really ready for real-world use yet and it's future is also unclear.
